apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-8080
  namespace: client-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-8080
  template:
    metadata:
      labels:
        app: app-8080
    spec:
      containers:
      - name: app
        image: app-8080:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
